export const TEXTS = {
    TR: {
        score: 'PUAN', gameOver: 'OYUN BİTTİ', gameWon: 'TEBRİKLER', replay: 'TEKRAR OYNA', menu: 'ANA MENÜ', exit: 'ÇIKIŞ', paused: 'OYUN DURAKLATILDI', resume: 'DEVAM ET',
        aiDisclaimer: 'OYUNUNU ÖLÜMSÜZLEŞTİR! 🎬',
        aiInstruction: 'Bu dosyayı indirip Replay Viewer ile tekrar izleyebilir, ekran kaydı alıp harika hamlelerini sosyal medyada paylaşabilirsin!',
        replayViewer: 'REPLAY VIEWER',
        back: 'GERİ',
        loadGameData: 'Oyun Verisi Yükle',
        uploadGameData: 'OYUN VERİSİ YÜKLE',
        play: 'OYNAT',
        pause: 'DURAKLAT',
        reset: 'SIFIRLA',
        speed: 'Hız',
        step: 'Adım',
        move: 'Hamle',
        rotateDevice: 'Lütfen cihazınızı dikey konuma getirin.'
    },
    EN: {
        score: 'PTS', gameOver: 'GAME OVER', gameWon: 'CONGRATULATIONS', replay: 'PLAY AGAIN', menu: 'MAIN MENU', exit: 'EXIT', paused: 'GAME PAUSED', resume: 'RESUME',
        aiDisclaimer: 'IMMORTALIZE YOUR GAME! 🎬',
        aiInstruction: 'Download this file to watch it in Replay Viewer, record your screen, and share your amazing moves on social media!',
        replayViewer: 'REPLAY VIEWER',
        back: 'BACK',
        loadGameData: 'Load Game Data',
        uploadGameData: 'UPLOAD GAME DATA',
        play: 'PLAY',
        pause: 'PAUSE',
        reset: 'RESET',
        speed: 'Speed',
        step: 'Step',
        move: 'Move',
        rotateDevice: 'Please rotate your device to portrait mode.'
    },
    ES: {
        score: 'PTS', gameOver: 'JUEGO TERMINADO', gameWon: 'FELICIDADES', replay: 'JUGAR DE NUEVO', menu: 'MENÚ PRINCIPAL', exit: 'SALIR', paused: 'JUEGO PAUSADO', resume: 'REANUDAR',
        aiDisclaimer: '¡INMORTALIZA TU JUEGO! 🎬',
        aiInstruction: '¡Descarga este archivo para verlo en Replay Viewer, graba tu pantalla y comparte tus increíbles movimientos en las redes sociales!',
        replayViewer: 'VISOR DE REPETICIÓN',
        back: 'ATRÁS',
        loadGameData: 'Cargar Datos',
        uploadGameData: 'CARGAR DATOS',
        play: 'REPRODUCIR',
        pause: 'PAUSA',
        reset: 'REINICIAR',
        speed: 'Velocidad',
        step: 'Paso',
        move: 'Movimiento',
        rotateDevice: 'Por favor, gire su dispositivo a modo vertical.'
    },
    DE: {
        score: 'PKT', gameOver: 'SPIEL VORBEI', gameWon: 'GLÜCKWUNSCH', replay: 'NOCHMAL SPIELEN', menu: 'HAUPTMENÜ', exit: 'BEENDEN', paused: 'PAUSE', resume: 'WEITER',
        aiDisclaimer: 'VEREWIGE DEIN SPIEL! 🎬',
        aiInstruction: 'Lade diese Datei herunter, um sie im Replay Viewer anzusehen, nimm deinen Bildschirm auf und teile deine tollen Züge in den sozialen Medien!',
        replayViewer: 'REPLAY VIEWER',
        back: 'ZURÜCK',
        loadGameData: 'Spieldaten Laden',
        uploadGameData: 'SPIELDATEN HOCHLADEN',
        play: 'ABSPIELEN',
        pause: 'PAUSE',
        reset: 'ZURÜCKSETZEN',
        speed: 'Geschw.',
        step: 'Schritt',
        move: 'Zug',
        rotateDevice: 'Bitte drehen Sie Ihr Gerät ins Hochformat.'
    },
    FR: {
        score: 'PTS', gameOver: 'JEU TERMINÉ', gameWon: 'FÉLICITATIONS', replay: 'REJOUER', menu: 'MENU PRINCIPAL', exit: 'QUITTER', paused: 'PAUSE', resume: 'REPRENDRE',
        aiDisclaimer: 'IMMORTALISEZ VOTRE JEU ! 🎬',
        aiInstruction: 'Téléchargez ce fichier pour le regarder dans Replay Viewer, enregistrez votre écran et partagez vos mouvements incroyables sur les réseaux sociaux !',
        replayViewer: 'VISIONNEUSE',
        back: 'RETOUR',
        loadGameData: 'Charger Données',
        uploadGameData: 'CHARGER DONNÉES',
        play: 'LECTURE',
        pause: 'PAUSE',
        reset: 'RÉINITIALISER',
        speed: 'Vitesse',
        step: 'Étape',
        move: 'Mouv.',
        rotateDevice: 'Veuillez faire pivoter votre appareil en mode portrait.'
    },
    IT: {
        score: 'PTI', gameOver: 'GAME OVER', gameWon: 'CONGRATULAZIONI', replay: 'GIOCA ANCORA', menu: 'MENU PRINCIPALE', exit: 'ESCI', paused: 'PAUSA', resume: 'RIPRENDI',
        aiDisclaimer: 'IMMORTALA IL TUO GIOCO! 🎬',
        aiInstruction: 'Scarica questo file per guardarlo nel Replay Viewer, registra lo schermo e condividi le tue mosse incredibili sui social media!',
        replayViewer: 'VISUALIZZATORE',
        back: 'INDIETRO',
        loadGameData: 'Carica Dati',
        uploadGameData: 'CARICA DATI',
        play: 'RIPRODUCI',
        pause: 'PAUSA',
        reset: 'RESET',
        speed: 'Velocità',
        step: 'Passo',
        move: 'Mossa',
        rotateDevice: 'Ruota il dispositivo in modalità verticale.'
    },
    JP: {
        score: '点', gameOver: 'ゲームオーバー', gameWon: 'おめでとう', replay: 'もう一度プレイ', menu: 'メインメニュー', exit: '終了', paused: '一時停止', resume: '再開',
        aiDisclaimer: 'ゲームを永遠に！ 🎬',
        aiInstruction: 'このファイルをダウンロードしてReplay Viewerで視聴し、画面を録画して素晴らしい動きをソーシャルメディアで共有しましょう！',
        replayViewer: 'リプレイビューア',
        back: '戻る',
        loadGameData: 'データ読み込み',
        uploadGameData: 'データをアップロード',
        play: '再生',
        pause: '一時停止',
        reset: 'リセット',
        speed: '速度',
        step: 'ステップ',
        move: '移動',
        rotateDevice: 'デバイスを縦向きに回転させてください。'
    },
    KR: {
        score: '점수', gameOver: '게임 오버', gameWon: '축하합니다', replay: '다시 하기', menu: '메인 메뉴', exit: '종료', paused: '일시 정지', resume: '계속',
        aiDisclaimer: '게임을 영원히 간직하세요! 🎬',
        aiInstruction: '이 파일을 다운로드하여 Replay Viewer에서 다시 보고, 화면을 녹화하여 멋진 움직임을 소셜 미디어에 공유하세요!',
        replayViewer: '리플레이 뷰어',
        back: '뒤로',
        loadGameData: '데이터 불러오기',
        uploadGameData: '데이터 업로드',
        play: '재생',
        pause: '일시 정지',
        reset: '초기화',
        speed: '속도',
        step: '단계',
        move: '이동',
        rotateDevice: '기기를 세로 모드로 회전해주세요.'
    },
    CN: {
        score: '分', gameOver: '游戏结束', gameWon: '恭喜', replay: '重玩', menu: '主菜单', exit: '退出', paused: '暂停', resume: '继续',
        aiDisclaimer: '让你的游戏不朽！ 🎬',
        aiInstruction: '下载此文件以在 Replay Viewer 中观看，录制屏幕并在社交媒体上分享你的精彩操作！',
        replayViewer: '回放查看器',
        back: '返回',
        loadGameData: '加载数据',
        uploadGameData: '上传数据',
        play: '播放',
        pause: '暂停',
        reset: '重置',
        speed: '速度',
        step: '步',
        move: '移动',
        rotateDevice: '请将设备旋转至纵向模式。'
    },
    RU: {
        score: 'ОЧК', gameOver: 'ИГРА ОКОНЧЕНА', gameWon: 'ПОЗДРАВЛЯЕМ', replay: 'ИГРАТЬ СНОВА', menu: 'ГЛАВНОЕ МЕНЮ', exit: 'ВЫХОД', paused: 'ПАУЗА', resume: 'ПРОДОЛЖИТЬ',
        aiDisclaimer: 'УВЕКОВЕЧЬ СВОЮ ИГРУ! 🎬',
        aiInstruction: 'Скачайте этот файл, чтобы посмотреть его в Replay Viewer, запишите экран и поделитесь своими крутыми ходами в социальных сетях!',
        replayViewer: 'ПРОСМОТР ПОВТОРА',
        back: 'НАЗАД',
        loadGameData: 'Загрузить Данные',
        uploadGameData: 'ЗАГРУЗИТЬ ДАННЫЕ',
        play: 'ИГРАТЬ',
        pause: 'ПАУЗА',
        reset: 'СБРОС',
        speed: 'Скорость',
        step: 'Шаг',
        move: 'Ход',
        rotateDevice: 'Пожалуйста, поверните устройство вертикально.'
    },
    AR: {
        score: 'نقاط', gameOver: 'انتهت اللعبة', gameWon: 'تهانينا', replay: 'العب مرة أخرى', menu: 'القائمة الرئيسية', exit: 'خروج', paused: 'موقوف', resume: 'استأنف',
        aiDisclaimer: 'خلّد لعبتك! 🎬',
        aiInstruction: 'قم بتنزيل هذا الملف لمشاهدته في Replay Viewer، وسجل شاشتك وشارك تحركاتك المذهلة على وسائل التواصل الاجتماعي!',
        replayViewer: 'عارض الإعادة',
        back: 'رجوع',
        loadGameData: 'تحميل البيانات',
        uploadGameData: 'تحميل بيانات اللعبة',
        play: 'تشغيل',
        pause: 'إيقاف مؤقت',
        reset: 'إعادة تعيين',
        speed: 'السرعة',
        step: 'خطوة',
        move: 'حركة',
        rotateDevice: 'يرجى تدوير جهازك إلى الوضع العمودي.'
    },
    PT: {
        score: 'PTS', gameOver: 'FIM DE JOGO', gameWon: 'PARABÉNS', replay: 'JOGAR NOVAMENTE', menu: 'MENU PRINCIPAL', exit: 'SAIR', paused: 'PAUSADO', resume: 'CONTINUAR',
        aiDisclaimer: 'IMORTALIZE SEU JOGO! 🎬',
        aiInstruction: 'Baixe este arquivo para assistir no Replay Viewer, grave sua tela e compartilhe suas jogadas incríveis nas redes sociais!',
        replayViewer: 'VISUALIZADOR',
        back: 'VOLTAR',
        loadGameData: 'Carregar Dados',
        uploadGameData: 'CARREGAR DADOS',
        play: 'REPRODUZIR',
        pause: 'PAUSA',
        reset: 'REDEFINIR',
        speed: 'Velocidade',
        step: 'Passo',
        move: 'Movimento',
        rotateDevice: 'Por favor, gire seu dispositivo para o modo retrato.'
    },
    NL: {
        score: 'PTN', gameOver: 'SPEL AFGELOPEN', gameWon: 'GEFELICITEERD', replay: 'OPNIEUW SPELEN', menu: 'HOOFDMENU', exit: 'AFSLUITEN', paused: 'GEPAUZEERD', resume: 'HERVATTEN',
        aiDisclaimer: 'VEREWIG JE SPEL! 🎬',
        aiInstruction: 'Download dit bestand om het in Replay Viewer te bekijken, neem je scherm op en deel je geweldige zetten op sociale media!',
        replayViewer: 'REPLAY VIEWER',
        back: 'TERUG',
        loadGameData: 'Laad Spelgegevens',
        uploadGameData: 'UPLOAD SPELGEGEVENS',
        play: 'AFSPELEN',
        pause: 'PAUZE',
        reset: 'RESETTEN',
        speed: 'Snelheid',
        step: 'Stap',
        move: 'Zet',
        rotateDevice: 'Draai uw apparaat naar portretmodus.'
    },
    SE: {
        score: 'PNG', gameOver: 'SPELET SLUT', gameWon: 'GRATTIS', replay: 'SPELA IGEN', menu: 'HUVUDMENY', exit: 'AVSLUTA', paused: 'PAUSAD', resume: 'FORTSÄTT',
        aiDisclaimer: 'FÖREVIGA DITT SPEL! 🎬',
        aiInstruction: 'Ladda ner den här filen för att titta på den i Replay Viewer, spela in din skärm och dela dina fantastiska drag på sociala medier!',
        replayViewer: 'REPLAY VIEWER',
        back: 'TILLBAKA',
        loadGameData: 'Ladda Speldata',
        uploadGameData: 'LADDA UPP SPELDATA',
        play: 'SPELA',
        pause: 'PAUS',
        reset: 'ÅTERSTÄLL',
        speed: 'Hastighet',
        step: 'Steg',
        move: 'Drag',
        rotateDevice: 'Vänligen rotera din enhet till porträttläge.'
    },
    NO: {
        score: 'PNG', gameOver: 'SPILLET ER OVER', gameWon: 'GRATULERER', replay: 'SPILL IGJEN', menu: 'HOVEDMENY', exit: 'AVSLUTT', paused: 'PAUSE', resume: 'FORTSETT',
        aiDisclaimer: 'FOREVIG SPILLET DITT! 🎬',
        aiInstruction: 'Last ned denne filen for å se den i Replay Viewer, ta opp skjermen din og del de fantastiske trekkene dine på sosiale medier!',
        replayViewer: 'REPLAY VIEWER',
        back: 'TILBAKE',
        loadGameData: 'Last Spilldata',
        uploadGameData: 'LAST OPP SPILLDATA',
        play: 'SPILL',
        pause: 'PAUSE',
        reset: 'NULLSTILL',
        speed: 'Hastighet',
        step: 'Trinn',
        move: 'Trekk',
        rotateDevice: 'Vennligst roter enheten til portrettmodus.'
    },
    DK: {
        score: 'PNT', gameOver: 'SPILLET ER SLUT', gameWon: 'TILLYKKE', replay: 'SPIL IGEN', menu: 'HOVEDMENU', exit: 'AFSLUT', paused: 'PAUSE', resume: 'FORTSÆT',
        aiDisclaimer: 'UDØDELIGGØR DIT SPIL! 🎬',
        aiInstruction: 'Download denne fil for at se den i Replay Viewer, optag din skærm og del dine fantastiske træk på sociale medier!',
        replayViewer: 'REPLAY VIEWER',
        back: 'TILBAGE',
        loadGameData: 'Indlæs Spildata',
        uploadGameData: 'UPLOAD SPILDATA',
        play: 'AFSPIL',
        pause: 'PAUSE',
        reset: 'NULSTIL',
        speed: 'Hastighed',
        step: 'Trin',
        move: 'Træk',
        rotateDevice: 'Venligst roter din enhed til portrættilstand.'
    },
    FI: {
        score: 'PIST', gameOver: 'PELI OHI', gameWon: 'ONNEKSI OLKOON', replay: 'PELAA UUDELLEEN', menu: 'PÄÄVALIKKO', exit: 'LOPETA', paused: 'TAUKO', resume: 'JATKA',
        aiDisclaimer: 'IKUISTA PELISI! 🎬',
        aiInstruction: 'Lataa tämä tiedosto katsoaksesi sen Replay Viewerissä, tallenna näyttösi ja jaa upeat siirtosi sosiaalisessa mediassa!',
        replayViewer: 'REPLAY VIEWER',
        back: 'TAKAISIN',
        loadGameData: 'Lataa Pelitiedot',
        uploadGameData: 'LATAA PELITIEDOT',
        play: 'TOISTA',
        pause: 'TAUKO',
        reset: 'NOLLAA',
        speed: 'Nopeus',
        step: 'Askel',
        move: 'Siirto',
        rotateDevice: 'Käännä laite pystyasentoon.'
    },
    PL: {
        score: 'PKT', gameOver: 'KONIEC GRY', gameWon: 'GRATULACJE', replay: 'ZAGRAJ PONOWNIE', menu: 'MENU GŁÓWNE', exit: 'WYJŚCIE', paused: 'PAUZA', resume: 'WZNÓW',
        aiDisclaimer: 'UWIECZNIJ SWOJĄ GRĘ! 🎬',
        aiInstruction: 'Pobierz ten plik, aby obejrzeć go w Replay Viewer, nagraj ekran i udostępnij swoje niesamowite ruchy w mediach społecznościowych!',
        replayViewer: 'PRZEGLĄDARKA',
        back: 'WSTECZ',
        loadGameData: 'Wczytaj Dane',
        uploadGameData: 'PRZEŚLIJ DANE GRY',
        play: 'ODTWÓRZ',
        pause: 'PAUZA',
        reset: 'RESETUJ',
        speed: 'Prędkość',
        step: 'Krok',
        move: 'Ruch',
        rotateDevice: 'Proszę obrócić urządzenie do trybu pionowego.'
    },
    GR: {
        score: 'ΠΟΝ', gameOver: 'ΤΕΛΟΣ ΠΑΙΧΝΙΔΙΟΥ', gameWon: 'ΣΥΓΧΑΡΗΤΗΡΙΑ', replay: 'ΠΑΙΞΕ ΞΑΝΑ', menu: 'ΚΥΡΙΟ ΜΕΝΟΥ', exit: 'ΕΞΟΔΟΣ', paused: 'ΠΑΥΣΗ', resume: 'ΣΥΝΕΧΕΙΑ',
        aiDisclaimer: 'ΑΘΑΝΑΤΙΣΕ ΤΟ ΠΑΙΧΝΙΔΙ ΣΟΥ! 🎬',
        aiInstruction: 'Κατεβάστε αυτό το αρχείο για να το δείτε στο Replay Viewer, καταγράψτε την οθόνη σας και μοιραστείτε τις εκπληκτικές κινήσεις σας στα social media!',
        replayViewer: 'ΠΡΟΒΟΛΗ REPLAY',
        back: 'ΠΙΣΩ',
        loadGameData: 'Φόρτωση Δεδομένων',
        uploadGameData: 'ΜΕΤΑΦΟΡΤΩΣΗ ΔΕΔΟΜΕΝΩΝ',
        play: 'ΑΝΑΠΑΡΑΓΩΓΗ',
        pause: 'ΠΑΥΣΗ',
        reset: 'ΕΠΑΝΑΦΟΡΑ',
        speed: 'Ταχύτητα',
        step: 'Βήμα',
        move: 'Κίνηση',
        rotateDevice: 'Παρακαλώ περιστρέψτε τη συσκευή σας σε κάθετη λειτουργία.'
    },
    IL: {
        score: 'נק', gameOver: 'המשחק נגמר', gameWon: 'כל הכבוד', replay: 'שחק שוב', menu: 'תפריט ראשי', exit: 'יציאה', paused: 'מושהה', resume: 'המשך',
        aiDisclaimer: 'הנצח את המשחק שלך! 🎬',
        aiInstruction: 'הורד את הקובץ הזה כדי לצפות בו ב-Replay Viewer, הקלט את המסך שלך ושתף את המהלכים המדהימים שלך ברשתות החברתיות!',
        replayViewer: 'צופה בהילוכים חוזרים',
        back: 'חזור',
        loadGameData: 'טען נתונים',
        uploadGameData: 'העלה נתוני משחק',
        play: 'נגן',
        pause: 'השהה',
        reset: 'אפס',
        speed: 'מהירות',
        step: 'צעד',
        move: 'מהלך',
        rotateDevice: 'אנא סובב את המכשיר למצב לאורך.'
    },
    TR_AZ: {
        score: 'XAL', gameOver: 'OYUN BİTDİ', gameWon: 'TƏBRİKLƏR', replay: 'YENİDƏN OYNA', menu: 'ƏSAS MENYU', exit: 'ÇIXIŞ', paused: 'PAUZA', resume: 'DAVAM ET',
        aiDisclaimer: 'OYUNUNU ƏBƏDİLƏŞDİR! 🎬',
        aiInstruction: 'Bu faylı yükləyib Replay Viewer ilə yenidən izləyə, ekran qeydi alıb möhtəşəm gedişlərini sosial mediada paylaşa bilərsən!',
        replayViewer: 'REPLAY VIEWER',
        back: 'GERİ',
        loadGameData: 'Oyun Məlumatını Yüklə',
        uploadGameData: 'OYUN MƏLUMATINI YÜKLƏ',
        play: 'OYNAT',
        pause: 'PAUZA',
        reset: 'SIFIRLA',
        speed: 'Sürət',
        step: 'Addım',
        move: 'Gediş',
        rotateDevice: 'Zəhmət olmasa cihazınızı şaquli vəziyyətə gətirin.'
    },
    KZ: {
        score: 'ҰПАЙ', gameOver: 'ОЙЫН АЯҚТАЛДЫ', gameWon: 'ҚҰТТЫҚТАЙМЫЗ', replay: 'ҚАЙТА ОЙНАУ', menu: 'БАСТЫ МӘЗІР', exit: 'ШЫҒУ', paused: 'КІДІРІС', resume: 'ЖАЛҒАСТЫРУ',
        aiDisclaimer: 'ОЙЫНЫҢДЫ МӘҢГІЛІК ЕТ! 🎬',
        aiInstruction: 'Бұл файлды жүктеп алып, Replay Viewer арқылы қайта қараңыз, экранды жазып алып, керемет жүрістеріңізді әлеуметтік желілерде бөлісіңіз!',
        replayViewer: 'ҚАЙТАЛАУДЫ КӨРУ',
        back: 'АРТҚА',
        loadGameData: 'Деректерді Жүктеу',
        uploadGameData: 'ОЙЫН ДЕРЕКТЕРІН ЖҮКТЕУ',
        play: 'ОЙНАТУ',
        pause: 'КІДІРТУ',
        reset: 'ҚАЙТАРУ',
        speed: 'Жылдамдық',
        step: 'Қадам',
        move: 'Жүріс',
        rotateDevice: 'Құрылғыны тік режимге бұрыңыз.'
    },
    UZ: {
        score: 'BALL', gameOver: 'O‘YIN TUGADI', gameWon: 'TABRIKLAYMIZ', replay: 'QAYTA O‘YNASH', menu: 'BOSH MENYU', exit: 'CHIQISH', paused: 'PAUZA', resume: 'DAVOM ETISH',
        aiDisclaimer: 'O‘YININGNI ABADIYLASHTIR! 🎬',
        aiInstruction: 'Ushbu faylni yuklab olib, Replay Viewer orqali qayta tomosha qiling, ekran yozuvini oling va ajoyib yurishlaringizni ijtimoiy tarmoqlarda ulashing!',
        replayViewer: 'REPLAY VIEWER',
        back: 'ORTGA',
        loadGameData: 'O‘yin Ma’lumotlarini Yuklash',
        uploadGameData: 'O‘YIN MA’LUMOTLARINI YUKLASH',
        play: 'O‘YNATISH',
        pause: 'PAUZA',
        reset: 'QAYTA SOZLASH',
        speed: 'Tezlik',
        step: 'Qadam',
        move: 'Yurish',
        rotateDevice: 'Iltimos, qurilmangizni vertikal holatga o‘tkazing.'
    },
    TM: {
        score: 'UTUK', gameOver: 'OÝUN GUTARDY', gameWon: 'GUTLAÝARYS', replay: 'TÄZEDEN OÝNAMAK', menu: 'BAŞ MENÝU', exit: 'ÇYKYŞ', paused: 'DURUZYLDY', resume: 'DOWAM ET',
        aiDisclaimer: 'OÝNUŇY BAKYLAŞDYR! 🎬',
        aiInstruction: 'Bu faýly ýükläp alyp, Replay Viewer bilen gaýtadan görüp, ekran ýazgysyny alyp we ajaýyp hereketleriňizi sosial mediada paýlaşyp bilersiňiz!',
        replayViewer: 'REPLAY VIEWER',
        back: 'YZYNA',
        loadGameData: 'Oýun Maglumatlaryny Ýükle',
        uploadGameData: 'OÝUN MAGLUMATLARYNY ÝÜKLE',
        play: 'OÝNAT',
        pause: 'DURUZ',
        reset: 'ARASSALA',
        speed: 'Tizlik',
        step: 'Ädim',
        move: 'Hereket',
        rotateDevice: 'Enjamyňyzy dik moda öwüriň.'
    },
    KG: {
        score: 'УПАЙ', gameOver: 'ОЮН БҮТТҮ', gameWon: 'КУТТУКТАЙБЫЗ', replay: 'КАЙРА ОЙНОО', menu: 'БАШКЫ МЕНЮ', exit: 'ЧЫГУУ', paused: 'ТЫНЫГУУ', resume: 'УЛАНТУУ',
        aiDisclaimer: 'ОЮНУҢДУ ТҮБӨЛҮКТҮҮ КЫЛ! 🎬',
        aiInstruction: 'Бул файлды жүктөп алып, Replay Viewer аркылы кайра көрүңүз, экранды жаздырып алып, сонун жүрүштөрүңүздү социалдык тармактарда бөлүшүңүз!',
        replayViewer: 'REPLAY VIEWER',
        back: 'АРТКА',
        loadGameData: 'Оюн Маалыматын Жүктөө',
        uploadGameData: 'ОЮН МААЛЫМАТЫН ЖҮКТӨӨ',
        play: 'ОЙНОТУУ',
        pause: 'ТЫНЫГУУ',
        reset: 'КАЙТАРУУ',
        speed: 'Ылдамдык',
        step: 'Кадам',
        move: 'Жүрүш',
        rotateDevice: 'Түзмөгүңүздү тике абалга буруңуз.'
    }
};
